ProyectoPanol/ProyectoPanol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoPanol/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import home, lista_productos, poblar_bd, producto, producto_ficha, registro, carrito_compra, add_to_cart, remove_from_cart,clear_cart,buscar_productos, user_login, reponedor_depdiseño,reponedor_depinformatica, reponedor_depproductosdisponibles, reponedor_depproductosdadosdebaja, exportar_productos_a_excel_mantenedor,exportar_productos_a_excel_departamentoinformatica,exportar_productos_a_excel_departamentodiseño,exportar_productos_a_excel_productosdisponibles, exportar_productos_a_excel_productosdadosdebaja, todos_los_productos, determine_home_page, custom_logout, cambiar_contraseña, solicitud_exitosa, solicitud_prestamo,solicitudes, mis_solicitudes, editar_solicitud, notificaciones, obtener_notificaciones, marcar_leida

urlpatterns = [
    path('', determine_home_page, name='determine_home_page'),
    path('home/', home, name="home"),
    path('todos_los_productos', todos_los_productos, name="todos_los_productos"),
    path('poblar_bd', poblar_bd, name="poblar_bd"),
    path('producto/<action>/<id>', producto, name="Producto"),
    path('solicitud_prestamo/<int:producto_id>/', solicitud_prestamo, name='solicitud_prestamo'),
    path('producto_ficha/<id>', producto_ficha, name="producto_ficha"),
    path('registro/', registro, name='registro'),
    path('login/', user_login, name='login'),
    path('cambiar_contraseña/', cambiar_contraseña, name='cambiar_contraseña'),
    path('logout/', custom_logout, name='logout'),
    path('carrito_compra', carrito_compra, name="carrito_compra"),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('clear_cart/', clear_cart, name='clear_cart'),
    path('buscar/', buscar_productos, name='buscar_productos'),
    path('reponedor_depdiseño/', reponedor_depdiseño, name='reponedor_depdiseño'),
    path('reponedor_depinformatica/', reponedor_depinformatica, name='reponedor_depinformatica'),
    path('reponedor_depproductosdisponibles/', reponedor_depproductosdisponibles, name='reponedor_depproductosdisponibles'),
    path('reponedor_depproductosdadosdebaja/', reponedor_depproductosdadosdebaja, name='reponedor_depproductosdadosdebaja'),
    path('exportar_productos_a_excel_mantenedor/', exportar_productos_a_excel_mantenedor, name='exportar_productos_a_excel_mantenedor'),
    path('exportar_productos_a_excel_departamentoinformatica/', exportar_productos_a_excel_departamentoinformatica, name='exportar_productos_a_excel_departamentoinformatica'),
    path('exportar_productos_a_excel_departamentodiseño/', exportar_productos_a_excel_departamentodiseño, name='exportar_productos_a_excel_departamentodiseño'),
    path('exportar_productos_a_excel_productosdisponibles/', exportar_productos_a_excel_productosdisponibles, name='exportar_productos_a_excel_productosdisponibles'),
    path('exportar_productos_a_excel_productosdadosdebaja/', exportar_productos_a_excel_productosdadosdebaja, name='exportar_productos_a_excel_productosdadosdebaja'),
    path('solicitud/', solicitud_prestamo, name='solicitud_prestamo'),
    path('solicitud_exitosa/', solicitud_exitosa, name='solicitud_exitosa'),
    path('mis_solicitudes/', mis_solicitudes, name='mis_solicitudes'),
    path('solicitudes/', solicitudes, name='solicitudes'),
    path('editar_solicitud/<int:solicitud_id>/', editar_solicitud, name='editar_solicitud'),
    path('notificaciones/', notificaciones, name='notificaciones'),
    path('obtener-notificaciones/', obtener_notificaciones, name='obtener_notificaciones'),
    path('marcar_notificacion_leida/<int:notificacion_id>/', marcar_leida, name='marcar_leida'),
    path('lista-productos/', lista_productos, name='lista_productos'),
    
]


    

ProyectoPanol/core/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User, AbstractUser
# Create your models here.


# Create Modelo para Categoria


class Departamento(models.Model):
    idDepartamento = models.IntegerField(primary_key=True, verbose_name="Id de Departamento")
    depto = models.CharField(max_length=80, blank=False, null=False, verbose_name="Nombre del departamento")

    def __str__(self):
        return self.depto
    
class RolUsuario(models.Model):
    idRol = models.IntegerField(primary_key=True, verbose_name="Id Rol")
    rol = models.CharField(max_length=12, blank=False, null=False, verbose_name="Rol")

    def __str__(self):
        return self.rol
    
class EstadoUsuario(models.Model):
    idEstadoUsuario = models.IntegerField(primary_key=True, verbose_name="Id Estado")
    estadoUsuario = models.CharField(max_length=10, blank=False, null=False, verbose_name="Estado Usuario")

    def __str__(self):
        return self.estadoUsuario

class EstadoProducto(models.Model):
    idEstadoProducto = models.IntegerField(primary_key=True, verbose_name="Id Estado Producto")
    estadoProducto = models.CharField(max_length=20, blank=False, null=False, verbose_name="Estado Producto")

    def __str__(self):
        return self.estadoProducto

# Create Modelo para Productos

class Producto(models.Model):
    idProducto = models.AutoField(primary_key=True, verbose_name="Id de Producto")
    nombreProducto = models.CharField(max_length=80, blank=False, null=False, verbose_name="Nombre del producto")
    esFungible = models.BooleanField(max_length=80, blank=False, null=False, verbose_name="Es fungible")
    estadoProducto = models.ForeignKey(EstadoProducto, on_delete=models.DO_NOTHING, verbose_name="Estado del producto")
    marca = models.CharField(max_length=40, blank=False, null=False, verbose_name="Marca")
    modelo = models.CharField(max_length=20, blank=False, null=False, verbose_name="Modelo")
    stock = models.IntegerField(null=False, blank=False, verbose_name="Stock")
    stockMinimo = models.IntegerField(null=False, blank=False, verbose_name="Stock Minimo")
    descripcion = models.CharField(max_length=200, blank=False, null=False, verbose_name="Descripcion del producto")
    imagen = models.ImageField(upload_to="images/", default="sinfoto.jpg", null=False, blank=False, verbose_name="Imagen")
    departamento = models.ForeignKey(Departamento, on_delete=models.DO_NOTHING, verbose_name="Departamento")
    ubicacionRack = models.IntegerField(blank=False, null=False, validators=[MinValueValidator(1), MaxValueValidator(12)], verbose_name="Rack")

    def __str__(self):
        return str(self.idProducto)
    
    class Meta:
        permissions = [
            ("can_view_producto", "Puede ver la página de productos"),
        ]
    
    
class Cart(models.Model):
    user = models.ForeignKey('core.CustomUser', on_delete=models.CASCADE)
    products = models.ManyToManyField('Producto', through='CartItem')

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey('Producto', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)



class CustomUser(AbstractUser):
    idUsuario = models.AutoField(primary_key=True)
    correo = models.EmailField(unique=True, max_length=60)
    sede = models.CharField(max_length=45)
    rol = models.ForeignKey(RolUsuario, on_delete=models.DO_NOTHING, default=1)
    estadoUsuario = models.ForeignKey(EstadoUsuario, on_delete=models.DO_NOTHING, default=1)
    departamento = models.ForeignKey(Departamento, on_delete=models.DO_NOTHING, default=1)

    # Agregar related_name para evitar el conflicto de nombres
    groups = models.ManyToManyField(
        'auth.Group',
        blank=True,
        related_name='custom_user_groups'  # Cambia el nombre como prefieras
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        blank=True,
        related_name='custom_user_permissions'  # Cambia el nombre como prefieras
    )

    def __str__(self):
        return self.username
    def save(self, *args, **kwargs):
        # Asigna automáticamente el valor 1 a 'estado' al crear un nuevo usuario
        if not self.idUsuario:
            estado = EstadoUsuario.objects.get(idEstadoUsuario=1)
            self.estado = estado
        super().save(*args, **kwargs)



class Solicitud(models.Model):
    idSolicitud = models.AutoField(primary_key=True, verbose_name="Id de Solicitud")
    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='solicitudes', verbose_name="Usuario")
    fecha_solicitud = models.DateTimeField(default=timezone.now, verbose_name="Fecha de Solicitud")
    fecha_retiro = models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Retiro")
    fecha_devolucion = models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Devolución")
    fecha_devolucion_efectiva = models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Devolución Efectiva")
    estaAprobado = models.BooleanField(default=False, verbose_name="Está Aprobado")
    productos = models.ManyToManyField(Producto, through='ProductosSolicitud', related_name='solicitudes', verbose_name="Productos")
    comentarios = models.TextField(blank=True, verbose_name="Comentarios")
    

    def save(self, *args, **kwargs):
        # Si la fecha de retiro se establece, calcula automáticamente la fecha de devolución
        if self.fecha_retiro:
            self.fecha_devolucion = self.fecha_retiro + timezone.timedelta(days=7)
        super().save(*args, **kwargs)


class ProductosSolicitud(models.Model):
    idProductosSolicitud = models.AutoField(primary_key=True, verbose_name="Id de ProductosSolicitud")
    solicitud = models.ForeignKey(Solicitud, on_delete=models.CASCADE, verbose_name="Solicitud")
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name="Producto")
    cantidad = models.PositiveIntegerField(default=1, verbose_name="Cantidad")

class Notificacion(models.Model):
    TIPO_CHOICES = (
        ('envio_solicitud', 'Usuario ha enviado una solicitud'),
        ('aprobacion', 'Tu solicitud fue aprobada'),
        ('rechazo', 'Tu solicitud fue rechazada'),
        # Puedes agregar más tipos de notificaciones según tus necesidades
    )

    detalle = models.TextField()
    leido = models.BooleanField(default=False)
    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='nombre_notificaciones')
    tipo = models.CharField(max_length=20, choices=TIPO_CHOICES)
    fecha_notificacion = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        return f"{self.get_tipo_display()} - {self.usuario.username}"

ProyectoPanol/core/forms.py
from django import forms
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.forms import ModelForm, fields
from .models import Producto, CustomUser, RolUsuario, EstadoUsuario, EstadoProducto, Departamento, Solicitud, ProductosSolicitud


class ProductoForm(ModelForm):
    class Meta:
        model = Producto
        fields = ['idProducto', 'nombreProducto', 'esFungible', 'estadoProducto', 'marca', 'modelo', 'stock', 'stockMinimo', 'descripcion', 'imagen', 'departamento', 'ubicacionRack']

class CustomUserForm(UserCreationForm):
    password1 = forms.CharField(label='Contraseña (RUT sin digito verificador)', widget=forms.PasswordInput)
    EstadoUsuario = forms.HiddenInput(attrs={'value': 1})

    class Meta:
        model = CustomUser
        fields = ('username', 'correo', 'sede', 'rol', 'departamento', 'password1')

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        
        if not password1.isdigit() or len(password1) != 8:
            raise ValidationError("La contraseña debe ser un número de 8 dígitos sin letras.")
        
        return password1

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Las contraseñas no coinciden. Por favor, inténtalo de nuevo.")




class SolicitudForm(forms.ModelForm):
    class Meta:
        model = Solicitud
        fields = ['fecha_solicitud', 'fecha_retiro', 'fecha_devolucion_efectiva', 'estaAprobado']
        widgets = {
            'fecha_solicitud': forms.DateInput(attrs={'readonly': 'readonly'}),
            'fecha_retiro': forms.DateInput(attrs={'type': 'date'}),
            'fecha_devolucion_efectiva': forms.HiddenInput(),
            'estaAprobado': forms.HiddenInput(),
        }

    def clean(self):
        cleaned_data = super().clean()
        fecha_retiro = cleaned_data.get('fecha_retiro')

        # Calcula la fecha de devolución como 7 días después de la fecha de retiro
        if fecha_retiro:
            cleaned_data['fecha_devolucion_efectiva'] = fecha_retiro + timezone.timedelta(days=7)

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(SolicitudForm, self).__init__(*args, **kwargs)
        self.fields['fecha_solicitud'].widget.attrs['value'] = timezone.now().strftime('%Y-%m-%d')
        self.fields['fecha_devolucion_efectiva'].initial = None
        self.fields['estaAprobado'].initial = False

class EditarSolicitudForm(forms.ModelForm):
    OPCIONES_APROBADO = (
        (True, 'Aprobado'),
        (False, 'No Aprobado'),
    )

    estaAprobado = forms.ChoiceField(
        choices=OPCIONES_APROBADO,
        widget=forms.Select(attrs={'class': 'form-select'})
    )

    comentarios = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4})
    )

    class Meta:
        model = Solicitud
        fields = ['fecha_solicitud', 'fecha_retiro', 'fecha_devolucion_efectiva', 'estaAprobado', 'comentarios']

    def __init__(self, *args, **kwargs):
        super(EditarSolicitudForm, self).__init__(*args, **kwargs)
        self.fields['fecha_solicitud'].widget = forms.DateInput(attrs={'type': 'date'})
        self.fields['fecha_retiro'].widget = forms.DateInput(attrs={'type': 'date'})
        self.fields['fecha_devolucion_efectiva'].widget = forms.DateInput(attrs={'type': 'date'})

class ProductosSolicitudForm(forms.ModelForm):
    class Meta:
        model = ProductosSolicitud
        fields = ['producto', 'cantidad']

ProyectoPanol/core/templates/core/(PRUEBA_NOUSAR)producto_tienda.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../../static/ArtesanosApp/bootstrap/bootstrap-4.6.0-dist/css/bootstrap-grid.min.css" />
    <link rel="stylesheet" href="../../static/ArtesanosApp/style/style_producto_principal.css" />
    <link rel="stylesheet" href="../../static/ArtesanosApp/style/style_producto_principal.css" />
    <link rel="stylesheet" href="../../static/ArtesanosApp/style/style_producto.css" />

    <!-- JQUERY INVOKE -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>


    <title>Producto</title>
  </head>
<body class="mainClass">
    <div class="col-12 mastergrid1">
      <div class="container-fluid dimension-producto col-sm-12 col-8">
        <div class="row col-12">
          <div class="col-sm-12 col-md-8 col-lg-8 col-xl-8 producto-principal">
            <div class="container d-flex">
              <div class="wrapper">
                <div class="card">
                  <span class="off bg-dark">0% Oferta </span>
                  <div id="imagen_producto"class="text-center">
                    <img
                      id="main-image"
                      src="../../static/ArtesanosApp/image/nostock.jpg"
                    
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12 lateral">
            <div><h1 class="tag">Personalizable</h1></div>
            <div  ><h2 id="titulo_producto" class="page-header">Nombre del producto</h2></div>
            <div ><h2  id="precio_producto1" class="precio_producto" ></h2></div>
            <div>
              <a href=""><img class="fav" src="../../static/ArtesanosApp/image/corazon.png" /></a>
            </div>
            <div id="btn.carrito">
              <a href=""
                ><input class="butons" type="button" value="Agregar al carrito"
              /></a>
            </div>
            <div id="btn.carrito">
              <a href=""
                ><input class="butons" type="button" value="Comprar"
              /></a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid col-md-10 col-lg-10 col-xl-10 col-sm-12 mt-auto">
      <div class="row">
      <div  class="container text-center">
        <h1 id="descripcion_titulo">Nombre del Producto</h1>
      </div>
      <div  class="list-description d-block align-items-center ">
          <h3 id="descripcion_producto"></h3>
      </div>
    </div>  
    </div>


  </body>
</html> 

ProyectoPanol/core/templates/core/cambiar_contraseña.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}
    <title>Cambiar Contraseña</title>
{% endblock %}

{% block stylesheet %}
    {{ block.super }} <!-- Mantén los estilos de la plantilla base -->
    <link href="{% static 'core/css/cambiar_contrasena.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container-cambiar-contraseña">
    <div class="titulo-container">
        <h2>CAMBIAR CONTRASEÑA</h2>
    </div>
    <form method="post" id="cambiar-contraseña-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Cambiar Contraseña</button>
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const cambiarContraseñaForm = document.getElementById('cambiar-contraseña-form');
        cambiarContraseñaForm.addEventListener('submit', async function (e) {
            e.preventDefault();

            const formData = new FormData(cambiarContraseñaForm);
            const response = await fetch(cambiarContraseñaForm.action, {
                method: 'POST',
                body: formData,
            });

            if (response.ok) {
                const data = await response.json();
                Swal.fire({
                    icon: 'success',
                    title: 'Éxito',
                    text: data.message,
                }).then((result) => {
                    if (result.isConfirmed || result.isDismissed) {
                        window.location.href = '/login/'; // Reemplaza con la URL correcta
                    }
                });
            }
        });
    });
</script>

{% endblock %}

ProyectoPanol/core/templates/core/editar_solicitud.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}
    <title>Editar Solicitud</title>
{% endblock %}

{% block stylesheet %}
    {{ block.super }} <!-- Mantén los estilos de la plantilla base -->
    <link href="{% static 'core/css/editar_solicitud.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<h1>Editar Solicitud</h1>

<div class="product-form-container">
    <form method="post" id="editar-solicitud-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Guardar</button>
      <a href="{% url 'solicitudes' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const editarSolicitudForm = document.getElementById('editar-solicitud-form');
        editarSolicitudForm.addEventListener('submit', async function (e) {
            e.preventDefault();

            const formData = new FormData(editarSolicitudForm);
            const response = await fetch(editarSolicitudForm.action, {
                method: 'POST',
                body: formData,
            });

            if (response.ok) {
                const data = await response.json();
                Swal.fire({
                    icon: 'success',
                    title: 'Éxito',
                    text: data.message,
                }).then((result) => {
                    if (result.isConfirmed || result.isDismissed) {
                        window.location.href = '/solicitudes/'; // Reemplaza con la URL correcta
                    }
                });
            }
        });
    });
</script>
{% endblock %}

ProyectoPanol/core/templates/core/home.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}
    <title>Home Page</title>
{% endblock %}

{% block stylesheet %}
    {{ block.super }} <!-- Mantén los estilos de la plantilla base -->
    <link rel="stylesheet" href="{% static 'core/css/forms.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/home.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container-title">
    <img src="/media/images/Logo transparente.png" alt="Título de la imagen" style="display: block; margin: 0 auto; width: 500px; height: 150px;">
</div>

<form method="GET" action="{% url 'home' %}">
    <div class="container-buttons" style="text-align: center;">
        <div class="button-row">
            <a href="{% url 'reponedor_depdiseño' %}" class="btn btn-blue">
                <img src="{% static 'core/icons/diseño.png' %}" alt="Icono PC">
                <span>Productos de Diseño</span>
            </a>
            <a href="{% url 'reponedor_depinformatica' %}" class="btn btn-blue">
                <img src="{% static 'core/icons/pc.png' %}" alt="Icono PC">
                <span>Productos de Informática</span>
            </a>
            <a href="{% url 'reponedor_depproductosdisponibles' %}" class="btn btn-blue">
                <img src="{% static 'core/icons/disponible.png' %}" alt="Icono PC">
                <span>Productos Disponibles</span>
            </a>
        </div>
        <div class="button-row">
            <a href="{% url 'reponedor_depproductosdadosdebaja' %}" class="btn btn-blue">
                <img src="{% static 'core/icons/debaja.png' %}" alt="Icono PC">
                <span>Productos Dados de Baja</span>
            </a>
            <a href="{% url 'Producto' action='ins' id=-1 %}" class="btn btn-mantenedor btn-blue">
                <img src="{% static 'core/icons/todos_prod.png' %}" alt="Icono PC">
                <span>Mantenedor de Productos</span>
            </a>
        </div>
    </div>
</form>




{% endblock %}

ProyectoPanol/core/templates/core/mis_solicitudes.html
{% extends "core\base.html" %}

{% load static %}

{% block title %}
    <title>Mis solicitudes</title>
{% endblock %}

{% block stylesheet %}
    {{ block.super }} <!-- Mantén los estilos de la plantilla base -->
    <link href="{% static 'core/css/solicitudes.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<h1>Mis Solicitudes</h1>
<table class="solicitudes-tabla">
    <thead>
        <tr>
            <th>Id de Solicitud</th>
            <th>Usuario</th>
            <th>Fecha de Solicitud</th>
            <th>Fecha de retiro</th>
            <th>Fecha de devolucion</th>
            <th>Estado de la solicitud</th>
            <th>Productos solicitados</th>
        </tr>
    </thead>
    <tbody>
        {% for solicitud in solicitudes %}
        <tr>
            <td>{{ solicitud.idSolicitud }}</td>
            <td>{{ solicitud.usuario }}</td>
            <td>{{ solicitud.fecha_solicitud|date:"d/m/Y" }}</td>
            <td>{{ solicitud.fecha_retiro|date:"d/m/Y" }}</td>
            <td>{{ solicitud.fecha_devolucion|date:"d/m/Y" }}</td>
            <td>
                {% if solicitud.estaAprobado %}
                Aprobado
                {% else %}
                Rechazado
                {% endif %}
            </td>
            <td>
                <ul>
                    {% for producto_solicitud in solicitud.productossolicitud_set.all %}
                    <li>{{ producto_solicitud.producto.nombreProducto }} - Cantidad: {{ producto_solicitud.cantidad }}</li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

ProyectoPanol/core/templates/core/notificaciones.html
{% extends "core\base.html" %}

{% load static %}

{% block title %}
    <title>Solicitud exitosa</title>
{% endblock %}

{% block stylesheet %}
    {{ block.super }}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap">
    <link href="{% static 'core/css/notificaciones.css' %}" rel="stylesheet">
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'core/js/notificaciones.js' %}"></script>
{% endblock %}

{% block content %}
    <h1>Centro de notificaciones</h1>

    <div class="col-9 text-center mx-auto"> <!-- Agregada clase mx-auto para centrar la columna -->
        <div class="notifications-container text-left"> <!-- Agregada clase para centrar el contenedor de notificaciones -->
            <h3 class="mb-4 border-bottom pb-1 text-left"><strong>Notificaciones nuevas:</strong> <span class="badgebg-primary">0</span></h3>
            <span class="ajaxRes"></span>
            <ul class="list-group notif-list wider-list"> <!-- Agregada clase wider-list para ajustar el ancho -->
                Loading...
            </ul>
        </div>
        <!-- Agregar un elemento con el atributo data-url para almacenar la URL -->
        <div id="notificaciones" data-url="{% url 'obtener_notificaciones' %}"></div>
    </div>
    
    
{% endblock %}